# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jhcb5e8OanSSjBJ6NWOwyBlwvROvL1S-
"""

#LIST
#DISPLAY
numbers=[1,2,3,4,6,7]
print(numbers)
fruits=["apple","banana","cherry","mango"]
print(fruits)

#EMPTY LIST
empty_list=[]
print(empty_list)

#MIXED TYPE
mixed_types=[10, "hello", 3.14, True]
print(mixed_types)

#len()
nums=[1,12,17,7,30]
print(len(nums))
fruits=("mango","kiwi","strawberry")
print(len(fruits))

#INDEXING
numbers=[1,2,3,4,6,7]
print(nums[3])
fruits=["apple","banana","cherry","mango"]
print(fruits[2])

#SLICING
nums=[1,20,23,25,24]
print(nums[1:2])
fruits=("mango","kiwi","strawberry","apple")
print(fruits[2:3])

#SLICING

nums=[1,20,23,25,24]
nums[3]=67
print(nums)

#append
alpha=["j","k","b","h","v"]
alpha.append("t")
print(alpha)

#remove
alpha=["j","k","b","h","v"]
alpha.remove("b")
print(alpha)

#index()
nums=[1,2,3,2,5,4,6,7]
nums.index(1)
print(nums.index(1))

#count()
alpha=["j","j","k","t","h","v","k"]
print(alpha.count("k"))

#extend()
num1=[1,5,9,7]
num2=[2,6,8,4]
num1.extend(num2)
print(num1)

#insert
num1=[1,5,9,7]
num1.insert(2,30)
print(num1)

#SORT
#for ascending
nums=[1,8,10,30,12,95]
nums.sort()
print(nums)

#for descending
nums=[1,8,10,30,12,95]
nums.sort(reverse=True)
print(nums)

#QUESTION: TAKE 3 SUBJECTS FROM USER AND STORE IT IN A LIST
sub=[]
sub1=(input("Enter subject 1:"))
sub2=(input("Enter subject 2:"))
sub3=(input("Enter subject 3:"))
sub.append(sub1)
sub.append(sub2)
sub.append(sub3)
print(sub)